# Exercise 2
## Numpy

In [1]:
!pip install numpy

  Using cached numpy-1.26.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (61 kB)
Using cached numpy-1.26.1-cp39-cp39-macosx_11_0_arm64.whl (14.0 MB)


In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [11]:
a.ndim # number of dimensions, is it a 2 dimensional array or a 3 dimensional one?

2

In [12]:
a.dtype.name

'int64'

In [13]:
a.itemsize

8

In [15]:
a.size # total number of elements in the array. Product of elements of `shape`.

15

In [16]:
type(a)

numpy.ndarray

In [17]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### 1. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [24]:
a = np.arange(15).reshape(3, 5)
a.size # number of elements

15

In [25]:
a.itemsize # length of one array element in bytes

8

In [26]:
a.size * a.itemsize # total bytes consumed by the elements

120

### 2. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2

In [30]:
array1 = np.array([10, 0, 1, 2, 4, 9])
array2 = np.array([1, 2, 3])
np.setdiff1d(array1, array2)

array([ 0,  4,  9, 10])

### 3. Write a NumPy program to compute the cross product of two given vectors

In [34]:
x = [2, 3, 4]
y = [5, 6, 7]
np.cross(x, y)

array([-3,  6, -3])